version: '3'
services:
  web:
    image: docker-node-express-mongoapp
    build: ./web-site
    command: node server/server
    ports:
      - 4000:3000
    volumes:
      - ./web-site:/usr/src/app
      - /usr/src/app/node_modules

